<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-07T11:59:15 CEST" name="Suite" finished-at="2025-04-07T12:02:59 CEST" duration-ms="224480">
    <groups>
    </groups>
    <test started-at="2025-04-07T11:59:15 CEST" name="Test" finished-at="2025-04-07T12:02:59 CEST" duration-ms="224480">
      <class name="RegressionPagesTestCase.FacturePageTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:RegressionPagesTestCase.FacturePageTest@78691363]" started-at="2025-04-07T11:59:15 CEST" name="setup" finished-at="2025-04-07T11:59:19 CEST" duration-ms="4145" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="AffichageErrorChampsNomPrenom_FR6777()[pri:0, instance:RegressionPagesTestCase.FacturePageTest@78691363]" started-at="2025-04-07T11:59:19 CEST" name="AffichageErrorChampsNomPrenom_FR6777" finished-at="2025-04-07T12:00:34 CEST" duration-ms="74508" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AffichageErrorChampsNomPrenom_FR6777 -->
        <test-method is-config="true" signature="setup()[pri:0, instance:RegressionPagesTestCase.FacturePageTest@78691363]" started-at="2025-04-07T12:00:34 CEST" name="setup" finished-at="2025-04-07T12:00:38 CEST" duration-ms="3839" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="ConnecterUtilisateur()[pri:0, instance:RegressionPagesTestCase.FacturePageTest@78691363]" started-at="2025-04-07T12:00:38 CEST" name="ConnecterUtilisateur" finished-at="2025-04-07T12:01:46 CEST" duration-ms="68357" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ConnecterUtilisateur -->
        <test-method is-config="true" signature="setup()[pri:0, instance:RegressionPagesTestCase.FacturePageTest@78691363]" started-at="2025-04-07T12:01:46 CEST" name="setup" finished-at="2025-04-07T12:01:49 CEST" duration-ms="3191" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="MontantNegatifTest()[pri:0, instance:RegressionPagesTestCase.FacturePageTest@78691363]" started-at="2025-04-07T12:01:49 CEST" name="MontantNegatifTest" finished-at="2025-04-07T12:02:59 CEST" duration-ms="70024" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Le message d'erreur est affiché alors que le montant est valide ! expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Le message d'erreur est affiché alors que le montant est valide ! expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertFalse(Assert.java:79)
at RegressionPagesTestCase.FacturePageTest.MontantNegatifTest(FacturePageTest.java:31)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- MontantNegatifTest -->
      </class> <!-- RegressionPagesTestCase.FacturePageTest -->
      <class name="RegressionPagesTestCase.HomeRecPageTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:RegressionPagesTestCase.HomeRecPageTest@385c9627]" started-at="2025-04-07T11:59:15 CEST" name="setup" finished-at="2025-04-07T11:59:19 CEST" duration-ms="4235" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="AffichageMessageErrorZeroResultat_6764()[pri:0, instance:RegressionPagesTestCase.HomeRecPageTest@385c9627]" started-at="2025-04-07T11:59:19 CEST" name="AffichageMessageErrorZeroResultat_6764" finished-at="2025-04-07T12:00:39 CEST" duration-ms="79491" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AffichageMessageErrorZeroResultat_6764 -->
      </class> <!-- RegressionPagesTestCase.HomeRecPageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
